export const API_PRODUCT_START = "API_PRODUCT_START";
export const API_PRODUCT_SUCCESS = "API_PRODUCT_SUCCESS";
export const API_PRODUCT_FAILED = "API_PRODUCT_FAILED";
export const API_PRODUCT_FILL = "API_PRODUCT_FILL";
